name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [main]  # main 브랜치에 push할 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub가 제공하는 Ubuntu 런타임에서 실행

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 코드 내려받기

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build the site
        run: mkdocs build --strict  # site/ 디렉터리 생성, --strict : 누락된 링크나 문서가 있을 경우 실패하게 함 (선택 사항)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # site/ 결과물을 gh-pages 브랜치에 자동 푸시
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub가 기본 제공하는 인증 토큰 (별도 설정 필요 없음)
          publish_dir: ./site  # 빌드 결과물 경로
